spring:
  redis:
    host: localhost
    port: 6379
    password: Qwerty123
    database: 0
    embedded: false
  cache:
    type: redis
    time-to-live: 3600000
    cache-null-values: false
  application:
    name: SpringToDo
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: postgres
    password: 10031998
    driver-class-name: org.postgresql.Driver
